version: '3.9'  # Specify the Compose file format version

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: npm run start

networks:
  default:
    driver: bridge
